version: '3.9'

services:
  app:
    build:
      context: ../../../Downloads
      dockerfile: Dockerfile1
    ports:
      - "8080:80"
    container_name: app

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_PROTOCOL=http
      - NGROK_PORT=app:80
    ports:
      - "4040:4040"
    container_name: ngrok