version: '3.9'

services:
  php-apache:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    volumes:
      - ./www/:/var/www/html/
      - .env:/var/www/html/.env
    ports:
      - "8080:80"
    container_name: php-apache
